development:
  open_for_all: true
  server_address: "http://localhost:3000"

central_development:
  open_for_all: false
  server_address: "http://al-dev.firstprinciplesmanagement.de"

test:
  open_for_all: false
  server_address: "http://localhost:3000"

production:
  open_for_all: false
  server_address: "http://al-prod.firstprinciplesmanagement.de"

public_production:
  open_for_all: true
  server_address: "http://al-public.firstprinciplesmanagement.de"

